proxy:
  image: kuzzleio/proxy:1.0.0-RC6
  ports:
    - "7511-7513:7511-7513"

kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC7
  links:
    - elasticsearch
    - redis
    - proxy
  environment:
    - kuzzle_services__db__host=elasticsearch
    - kuzzle_services__internalCache__node__host=redis
    - kuzzle_services__memoryStorage__node__host=redis
    - kuzzle_services__proxyBroker__host=proxy

redis:
  image: redis:3.2-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4

kuzzleBo:
  image: kuzzleio/bo:latest
  ports:
    - "3000:3000"
  links:
    - proxy:kuzzle
  environment:
    - KUZZLE_URL
